import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1715500800000 implements MigrationInterface {
    name = 'InitialSchema1715500800000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "rooms" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "branchId" uuid NOT NULL, "name" character varying(100) NOT NULL, "capacity" integer NOT NULL DEFAULT '12', "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0368a2d7c215f2d0458a54933f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9b3bf54c5642f80b94ba4e881a" ON "rooms" ("branchId", "name") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "address" character varying(255), "phone" character varying(30), "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c776bc512f80899e42dacdf22d" ON "branches" ("name") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TABLE "course_categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "description" character varying(500), CONSTRAINT "PK_626794960514393da07e942f8d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_eb2d3fdddd2fbe23736362ae3d" ON "course_categories" ("name") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."courses_status_enum" AS ENUM('ACTIVE', 'INACTIVE')`);
        await queryRunner.query(`CREATE TABLE "courses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(150) NOT NULL, "description" text, "categoryId" uuid, "durationMonths" integer NOT NULL DEFAULT '3', "price" numeric(12,2) NOT NULL, "status" "public"."courses_status_enum" NOT NULL DEFAULT 'ACTIVE', "color" character varying(20), CONSTRAINT "PK_3f70a487cc718ad8eda4e6d58c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_32e4717dac0c40e13356a7ce20" ON "courses" ("name") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_c730473dfb837b3e62057cd944" ON "courses" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_889f2701163f86b2faf62a6247" ON "courses" ("status") `);
        await queryRunner.query(`CREATE TABLE "parents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "studentId" uuid NOT NULL, "fullName" character varying(150) NOT NULL, "phone" character varying(30) NOT NULL, "relation" character varying(50) NOT NULL DEFAULT 'PARENT', "isPrimary" boolean NOT NULL DEFAULT false, "telegramChatId" bigint, CONSTRAINT "PK_9a4dc67c7b8e6a9cb918938d353" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_915830b486e30ddbb7b7eb4849" ON "parents" ("studentId") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(100) NOT NULL, "module" character varying(50) NOT NULL, "description" character varying(255) NOT NULL, CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8dad765629e83229da6feda1c1" ON "permissions" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_8b634526cdd01f2adba6c7ac07" ON "permissions" ("module") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(50) NOT NULL, "description" character varying(255), "isSystem" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "tokenHash" character varying(128) NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL, "revokedAt" TIMESTAMP WITH TIME ZONE, "userAgent" character varying(500), "ip" character varying(64), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c25bc63d248ca90e8dcc1d92d0" ON "refresh_tokens" ("tokenHash") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phone" character varying(30), "avatarUrl" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "telegramChatId" bigint, "lastLoginAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_262d8d714a42e664d987714a75" ON "users" ("email") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."students_gender_enum" AS ENUM('MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TYPE "public"."students_status_enum" AS ENUM('ACTIVE', 'INACTIVE', 'GRADUATED', 'DROPPED')`);
        await queryRunner.query(`CREATE TABLE "students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "middleName" character varying(100), "gender" "public"."students_gender_enum", "birthDate" date, "phone" character varying(30) NOT NULL, "email" character varying(255), "passportSeries" character varying(20), "passportNumber" character varying(30), "address" character varying(500), "photoUrl" character varying(500), "emergencyContactName" character varying(150), "emergencyContactPhone" character varying(30), "status" "public"."students_status_enum" NOT NULL DEFAULT 'ACTIVE', "notes" text, "telegramChatId" bigint, "branchId" uuid, CONSTRAINT "REL_e0208b4f964e609959aff431bf" UNIQUE ("userId"), CONSTRAINT "PK_7d7f07271ad4ce999880713f05e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_70e820177fa11cc56cbbc8d712" ON "students" ("userId") WHERE "userId" IS NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_283207a7d7f4751ba08124d385" ON "students" ("phone") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_89d97b30d7d2b126c22e4fb28d" ON "students" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb0352ae520aba43785c16247c" ON "students" ("branchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c013e829148a48bc61bdfa2a8a" ON "students" ("lastName", "firstName") `);
        await queryRunner.query(`CREATE TYPE "public"."group_students_status_enum" AS ENUM('ACTIVE', 'LEFT', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "group_students" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "groupId" uuid NOT NULL, "studentId" uuid NOT NULL, "joinedAt" date NOT NULL, "leftAt" date, "discountPercent" numeric(5,2) NOT NULL DEFAULT '0', "status" "public"."group_students_status_enum" NOT NULL DEFAULT 'ACTIVE', "notes" text, CONSTRAINT "PK_cd596d1c8176853f748dc44af4b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_673797eb80fe17fe53d74ae049" ON "group_students" ("studentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e73ed9bc304c3e220713a7187b" ON "group_students" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9ebf1896c04afe06595504b178" ON "group_students" ("groupId", "studentId") `);
        await queryRunner.query(`CREATE TABLE "schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "groupId" uuid NOT NULL, "roomId" uuid, "weekday" smallint NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "effectiveFrom" date NOT NULL, "effectiveTo" date, CONSTRAINT "PK_7e33fc2ea755a5765e3564e66dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a34fb9d75013c4d3ae96ef331c" ON "schedules" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcb26377363823daf7e1d52bcd" ON "schedules" ("roomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c2aafe3b540e5b336ed4d4c93a" ON "schedules" ("weekday", "startTime", "endTime") `);
        await queryRunner.query(`CREATE TYPE "public"."teachers_salarytype_enum" AS ENUM('FIXED', 'PERCENT', 'PER_LESSON')`);
        await queryRunner.query(`CREATE TYPE "public"."teachers_status_enum" AS ENUM('ACTIVE', 'ON_LEAVE', 'TERMINATED')`);
        await queryRunner.query(`CREATE TABLE "teachers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "userId" uuid NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phone" character varying(30) NOT NULL, "specialization" character varying(150), "bio" text, "photoUrl" character varying(500), "hireDate" date, "salaryType" "public"."teachers_salarytype_enum" NOT NULL DEFAULT 'FIXED', "salaryAmount" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."teachers_status_enum" NOT NULL DEFAULT 'ACTIVE', "branchId" uuid, CONSTRAINT "REL_4d8041cbc103a5142fa2f2afad" UNIQUE ("userId"), CONSTRAINT "PK_a8d4f83be3abe4c687b0a0093c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4d8041cbc103a5142fa2f2afad" ON "teachers" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0065a2e73dc59f7dab68792c5d" ON "teachers" ("phone") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_8578016751718e693208ec8705" ON "teachers" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_76b79afff40620bd7c22f37660" ON "teachers" ("branchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_81ca4852536927400c41e1d8ce" ON "teachers" ("lastName", "firstName") `);
        await queryRunner.query(`CREATE TYPE "public"."groups_status_enum" AS ENUM('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying(100) NOT NULL, "courseId" uuid NOT NULL, "teacherId" uuid, "roomId" uuid, "branchId" uuid, "startDate" date NOT NULL, "endDate" date, "monthlyFee" numeric(12,2) NOT NULL, "capacity" integer NOT NULL DEFAULT '12', "status" "public"."groups_status_enum" NOT NULL DEFAULT 'ACTIVE', "description" text, CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fd658dcd8a21e9331a3763f807" ON "groups" ("name") WHERE "deletedAt" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_89ce024cb71a24a02b09fb8f87" ON "groups" ("courseId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e63173ac43b478c2fc0cc20ac3" ON "groups" ("teacherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4115ffc9504b17d3abdc16ce55" ON "groups" ("roomId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d802bbcffd407a85b6e5a6075" ON "groups" ("branchId") `);
        await queryRunner.query(`CREATE INDEX "IDX_479d3d96102ea6e80113503c68" ON "groups" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."lessons_status_enum" AS ENUM('PLANNED', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "lessons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "groupId" uuid NOT NULL, "scheduleId" uuid, "teacherId" uuid, "roomId" uuid, "date" date NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "topic" character varying(255), "status" "public"."lessons_status_enum" NOT NULL DEFAULT 'PLANNED', CONSTRAINT "PK_9b9a8d455cac672d262d7275730" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_797de8c3f8e0c9f7fad2875bbf" ON "lessons" ("teacherId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5c441a71bcb99a93b949ad2eb5" ON "lessons" ("date") `);
        await queryRunner.query(`CREATE INDEX "IDX_913c2193a312392325ec82ea21" ON "lessons" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_02476d01406508d32587c16f24" ON "lessons" ("groupId", "date", "startTime") `);
        await queryRunner.query(`CREATE TYPE "public"."attendance_records_status_enum" AS ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED')`);
        await queryRunner.query(`CREATE TABLE "attendance_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "lessonId" uuid NOT NULL, "studentId" uuid NOT NULL, "status" "public"."attendance_records_status_enum" NOT NULL, "note" character varying(255), "markedById" uuid, CONSTRAINT "PK_946920332f5bc9efad3f3023b96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_21f6cf258d12a2432bd2a8f798" ON "attendance_records" ("studentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f94ab929fdeb3864421b306bde" ON "attendance_records" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_58d46d7374ab10b6b5257c41e4" ON "attendance_records" ("lessonId", "studentId") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid, "userEmail" character varying(255), "action" character varying(50) NOT NULL, "entity" character varying(100) NOT NULL, "entityId" uuid, "oldValue" jsonb, "newValue" jsonb, "ip" character varying(64), "userAgent" character varying(500), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_2643f2a68c662985433dbddca1" ON "audit_logs" ("entity", "entityId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CASH', 'CARD', 'BANK_TRANSFER', 'CONTRACT')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('COMPLETED', 'REFUNDED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "number" character varying(30) NOT NULL, "studentId" uuid NOT NULL, "invoiceId" uuid, "groupId" uuid, "amount" numeric(12,2) NOT NULL, "method" "public"."payments_method_enum" NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'COMPLETED', "paidAt" TIMESTAMP WITH TIME ZONE NOT NULL, "description" character varying(500), "receivedById" uuid, "refundedAt" TIMESTAMP WITH TIME ZONE, "refundReason" character varying(500), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9a6b63632807e403e38e29c6b0" ON "payments" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_b2731e10aef7f886a08c552290" ON "payments" ("studentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_09739b0587054798a29e7eb17d" ON "payments" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2c0d278140eb683b4a6302d746" ON "payments" ("method") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_939f03487247fc2bdbc4ff6ab8" ON "payments" ("paidAt") `);
        await queryRunner.query(`CREATE TABLE "payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "paymentId" uuid NOT NULL, "invoiceId" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, CONSTRAINT "PK_a5c6ff22065ac772620c85f4efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6ef3658d2831bd99e2f848d55a" ON "payment_allocations" ("invoiceId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_61ab062aa0ec269de87395c4f3" ON "payment_allocations" ("paymentId", "invoiceId") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "number" character varying(30) NOT NULL, "studentId" uuid NOT NULL, "groupId" uuid, "enrollmentId" uuid, "periodMonth" date NOT NULL, "amount" numeric(12,2) NOT NULL, "paidAmount" numeric(12,2) NOT NULL DEFAULT '0', "dueDate" date NOT NULL, "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'PENDING', "description" character varying(255), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6b20aa66f2a835a4f2fbde4872" ON "invoices" ("number") `);
        await queryRunner.query(`CREATE INDEX "IDX_275c3d1cad7de2518d78dc81e5" ON "invoices" ("studentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3401d31eca9ff7cba51d563811" ON "invoices" ("groupId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f0fb4998923c6865508a6f74f" ON "invoices" ("periodMonth") `);
        await queryRunner.query(`CREATE INDEX "IDX_41ee6a6636d48aac700fb52e0b" ON "invoices" ("dueDate") `);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f4ce819b02a4a14f26d5288064" ON "invoices" ("enrollmentId", "periodMonth") WHERE "enrollmentId" IS NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('PAYMENT_RECEIVED', 'PAYMENT_REMINDER', 'DEBT_REMINDER', 'ATTENDANCE_MARKED', 'STUDENT_CREATED', 'GROUP_CHANGED', 'GROUP_ENROLLMENT', 'INVOICE_CREATED', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "userId" uuid NOT NULL, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "body" text NOT NULL, "data" jsonb, "isRead" boolean NOT NULL DEFAULT false, "readAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_5340fc241f57310d243e5ab20b" ON "notifications" ("userId", "isRead") `);
        await queryRunner.query(`CREATE TABLE "files" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "originalName" character varying(255) NOT NULL, "mimeType" character varying(100) NOT NULL, "size" integer NOT NULL, "path" character varying(500) NOT NULL, "category" character varying(100) NOT NULL DEFAULT 'general', "uploadedById" uuid, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_93c04123b9642879843a20d971" ON "files" ("path") `);
        await queryRunner.query(`CREATE INDEX "IDX_a525d85f0ac59aa9a971825e1a" ON "files" ("uploadedById") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_d430a02aad006d8a70f3acd7d03" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_88481b0c4ed9ada47e9fdd67475" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "rooms" ADD CONSTRAINT "FK_136aa30aa134259d9828c2d182e" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "courses" ADD CONSTRAINT "FK_c730473dfb837b3e62057cd9447" FOREIGN KEY ("categoryId") REFERENCES "course_categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "FK_915830b486e30ddbb7b7eb4849d" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_e0208b4f964e609959aff431bf9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "students" ADD CONSTRAINT "FK_fb0352ae520aba43785c16247c3" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD CONSTRAINT "FK_db9a438a218989ecaa69acc225e" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD CONSTRAINT "FK_673797eb80fe17fe53d74ae049b" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_a34fb9d75013c4d3ae96ef331c4" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD CONSTRAINT "FK_dcb26377363823daf7e1d52bcd2" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_4d8041cbc103a5142fa2f2afad4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teachers" ADD CONSTRAINT "FK_76b79afff40620bd7c22f37660a" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_89ce024cb71a24a02b09fb8f879" FOREIGN KEY ("courseId") REFERENCES "courses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_e63173ac43b478c2fc0cc20ac39" FOREIGN KEY ("teacherId") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_4115ffc9504b17d3abdc16ce557" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_3d802bbcffd407a85b6e5a60759" FOREIGN KEY ("branchId") REFERENCES "branches"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_4261adc75cbfa91fadc4fe297ec" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_8a62092e6333ec8c9458026927c" FOREIGN KEY ("scheduleId") REFERENCES "schedules"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_797de8c3f8e0c9f7fad2875bbf8" FOREIGN KEY ("teacherId") REFERENCES "teachers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lessons" ADD CONSTRAINT "FK_53ab941cb9fe26166ca42c305d6" FOREIGN KEY ("roomId") REFERENCES "rooms"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_231830e7ee273bf869f288767d0" FOREIGN KEY ("lessonId") REFERENCES "lessons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_records" ADD CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_b2731e10aef7f886a08c552290e" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_43d19956aeab008b49e0804c145" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_09739b0587054798a29e7eb17df" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_68129272bde8768a20d6967a62c" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_6ef3658d2831bd99e2f848d55a9" FOREIGN KEY ("invoiceId") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_275c3d1cad7de2518d78dc81e52" FOREIGN KEY ("studentId") REFERENCES "students"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_3401d31eca9ff7cba51d563811c" FOREIGN KEY ("groupId") REFERENCES "groups"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_01cf449922eb3ce2ff5af1b3a84" FOREIGN KEY ("enrollmentId") REFERENCES "group_students"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_01cf449922eb3ce2ff5af1b3a84"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_3401d31eca9ff7cba51d563811c"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_275c3d1cad7de2518d78dc81e52"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_6ef3658d2831bd99e2f848d55a9"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_68129272bde8768a20d6967a62c"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_09739b0587054798a29e7eb17df"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_43d19956aeab008b49e0804c145"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_b2731e10aef7f886a08c552290e"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_21f6cf258d12a2432bd2a8f798d"`);
        await queryRunner.query(`ALTER TABLE "attendance_records" DROP CONSTRAINT "FK_231830e7ee273bf869f288767d0"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_53ab941cb9fe26166ca42c305d6"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_797de8c3f8e0c9f7fad2875bbf8"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_8a62092e6333ec8c9458026927c"`);
        await queryRunner.query(`ALTER TABLE "lessons" DROP CONSTRAINT "FK_4261adc75cbfa91fadc4fe297ec"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_3d802bbcffd407a85b6e5a60759"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_4115ffc9504b17d3abdc16ce557"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_e63173ac43b478c2fc0cc20ac39"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_89ce024cb71a24a02b09fb8f879"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_76b79afff40620bd7c22f37660a"`);
        await queryRunner.query(`ALTER TABLE "teachers" DROP CONSTRAINT "FK_4d8041cbc103a5142fa2f2afad4"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_dcb26377363823daf7e1d52bcd2"`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP CONSTRAINT "FK_a34fb9d75013c4d3ae96ef331c4"`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP CONSTRAINT "FK_673797eb80fe17fe53d74ae049b"`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP CONSTRAINT "FK_db9a438a218989ecaa69acc225e"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_fb0352ae520aba43785c16247c3"`);
        await queryRunner.query(`ALTER TABLE "students" DROP CONSTRAINT "FK_e0208b4f964e609959aff431bf9"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "FK_915830b486e30ddbb7b7eb4849d"`);
        await queryRunner.query(`ALTER TABLE "courses" DROP CONSTRAINT "FK_c730473dfb837b3e62057cd9447"`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP CONSTRAINT "FK_136aa30aa134259d9828c2d182e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a525d85f0ac59aa9a971825e1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93c04123b9642879843a20d971"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5340fc241f57310d243e5ab20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4ce819b02a4a14f26d5288064"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41ee6a6636d48aac700fb52e0b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f0fb4998923c6865508a6f74f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3401d31eca9ff7cba51d563811"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_275c3d1cad7de2518d78dc81e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6b20aa66f2a835a4f2fbde4872"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_61ab062aa0ec269de87395c4f3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ef3658d2831bd99e2f848d55a"`);
        await queryRunner.query(`DROP TABLE "payment_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_939f03487247fc2bdbc4ff6ab8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c0d278140eb683b4a6302d746"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09739b0587054798a29e7eb17d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b2731e10aef7f886a08c552290"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a6b63632807e403e38e29c6b0"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2643f2a68c662985433dbddca1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58d46d7374ab10b6b5257c41e4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f94ab929fdeb3864421b306bde"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21f6cf258d12a2432bd2a8f798"`);
        await queryRunner.query(`DROP TABLE "attendance_records"`);
        await queryRunner.query(`DROP TYPE "public"."attendance_records_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02476d01406508d32587c16f24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_913c2193a312392325ec82ea21"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c441a71bcb99a93b949ad2eb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_797de8c3f8e0c9f7fad2875bbf"`);
        await queryRunner.query(`DROP TABLE "lessons"`);
        await queryRunner.query(`DROP TYPE "public"."lessons_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_479d3d96102ea6e80113503c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d802bbcffd407a85b6e5a6075"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4115ffc9504b17d3abdc16ce55"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e63173ac43b478c2fc0cc20ac3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89ce024cb71a24a02b09fb8f87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fd658dcd8a21e9331a3763f807"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TYPE "public"."groups_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81ca4852536927400c41e1d8ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76b79afff40620bd7c22f37660"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8578016751718e693208ec8705"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0065a2e73dc59f7dab68792c5d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d8041cbc103a5142fa2f2afad"`);
        await queryRunner.query(`DROP TABLE "teachers"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."teachers_salarytype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c2aafe3b540e5b336ed4d4c93a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcb26377363823daf7e1d52bcd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a34fb9d75013c4d3ae96ef331c"`);
        await queryRunner.query(`DROP TABLE "schedules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ebf1896c04afe06595504b178"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e73ed9bc304c3e220713a7187b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_673797eb80fe17fe53d74ae049"`);
        await queryRunner.query(`DROP TABLE "group_students"`);
        await queryRunner.query(`DROP TYPE "public"."group_students_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c013e829148a48bc61bdfa2a8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb0352ae520aba43785c16247c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89d97b30d7d2b126c22e4fb28d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_283207a7d7f4751ba08124d385"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70e820177fa11cc56cbbc8d712"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TYPE "public"."students_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."students_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_262d8d714a42e664d987714a75"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c25bc63d248ca90e8dcc1d92d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b634526cdd01f2adba6c7ac07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8dad765629e83229da6feda1c1"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_915830b486e30ddbb7b7eb4849"`);
        await queryRunner.query(`DROP TABLE "parents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_889f2701163f86b2faf62a6247"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c730473dfb837b3e62057cd944"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32e4717dac0c40e13356a7ce20"`);
        await queryRunner.query(`DROP TABLE "courses"`);
        await queryRunner.query(`DROP TYPE "public"."courses_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eb2d3fdddd2fbe23736362ae3d"`);
        await queryRunner.query(`DROP TABLE "course_categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c776bc512f80899e42dacdf22d"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b3bf54c5642f80b94ba4e881a"`);
        await queryRunner.query(`DROP TABLE "rooms"`);
    }

}
